######################################################################
# Automatically generated by qmake (2.01a) man. apr. 3 14:14:26 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += obstacleControl.h sensorsim.h sensorTest.h
SOURCES += environment.cpp obstacleControl.cpp sensorsim.cpp sensorTest.cpp
