AIS_range: 10000
radar_range: 5000
lidar_range: 5000

## AIS error parameters
AIS_position_bias_sigma: 1
AIS_COG_bias_sigma: 2
AIS_track_bias_sigma: 2
AIS_ROT_bias_sigma: 0.01
AIS_SOG_bias_sigma: 0.5

AIS_position_measure_sigma: 0.1
AIS_COG_measure_sigma: 0.1
AIS_track_measure_sigma: 0.5
AIS_ROT_measure_sigma: 0.01
AIS_SOG_measure_sigma: 0.5

AIS_position_bias_time_constant: 20
AIS_COG_bias_time_constant: 10
AIS_track_bias_time_constant: 10
AIS_ROT_bias_time_constant: 10
AIS_SOG_bias_time_constant: 20

## Radar error parameters
radar_position_bias_sigma: 0.5
radar_size_bias_sigma: 10

radar_position_bias_time_constant: 5
radar_size_bias_time_constant: 100

radar_position_measure_sigma: 1
radar_size_measure_sigma: 1

radar_position_error_pr_distance_gain: 0.002
radar_size_error_pr_distance_gain: 0.003

## LiDAR error parameters
lidar_position_bias_sigma: 0.1
lidar_size_bias_sigma: 10

lidar_position_bias_time_constant: 5
lidar_size_bias_time_constant: 100

lidar_position_measure_sigma: 0.1
lidar_size_measure_sigma: 1

lidar_position_error_pr_distance_gain: 0.002
lidar_size_error_pr_distance_gain: 0.003

